fun main(args: Array<String>) {
    var list:List<Int> = listOf(5,6,1,9,-4,7,8,2)
    println("Elements in List by index:")
    for(i in list.indices)
        print("${list[i]}\t")
    println()
    println("Elements in List by Item:")
    for(i in list)
        print("$i\t")
    println()
    println("Elements Sort up ascending:")
    var list2= list.sorted()
    for(i in list2)
        print("$i\t")
    println()
    println("Elements sort up descending:")
    var list3= list.sortedDescending()
    for(i in list3)
        print("$i\t")
    println()
    var list4=list.filter { x->x%2==0 }
    println("Even elements(filter function):")
    for(i in list4)
        print("$i\t")
    println()
    println("SUM="+list.sum())
    println("MAX="+list.maxOrNull())
    println("MIN="+list.minOrNull())
    println("AVERAGE="+list.average())
}
